version: '3.6'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201","tls_disable":"0", "tls_cert_file":"/data/server.crt", "tls_key_file":"/data/server.key"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: 'root'
      VAULT_TOKEN: 'root'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-certs:/data
    healthcheck:
      retries: 5
    command: server -dev -dev-root-token-id="root"
